### PR TITLE
Initial test setup

### PR DESCRIPTION
**Pull request by AB1908**

### CODE REVIEW

**Comment by mProjectsCode** [comment]
Looks good, but i think it is smarter to first merge #6 and then adjust this

**Comment by AB1908** [comment]
Oh my. Merge and then I'll resolve conflicts, I guess.

**Comment by mProjectsCode** [comment]
i can help you a bit, seeing as I rewrote everything xD

**Comment by mProjectsCode** [comment]
I resolved the conflicts, and i will add some more tests now

**Comment by mProjectsCode** [comment]
ok i added some more in 6749d1cd0b4e548b2666a338bce71f9bd0809995

**Pull request merged**
