### PR TITLE
Add public API declarations

### PR DESCRIPTION
**Pull request by AB1908**
Unfortunately, I forgot to switch branches before working on additional improvements. I'll stop with the current changes and switch.

Summary:
- Added public API def
- Added initial test for createField
- Added basic implementation for createField that passes the current tests
- Rewrote the mocks for `app.vault` and related Obsidian APIs
- Moved `stringifyYaml` to a separate module to make mocking and testing easier.

### CODE REVIEW

**Comment by AB1908** [comment]
Ah one more note, it appears I've duplicated some effort because I was too focused on trying to create a usable test bed. I'll probably have to rewrite parts of this before we merge it. I'm open to feedback on how you want to use this impl approach and fold in the pattern to your existing implementations.

**Comment by mProjectsCode** [comment]
I rewrote the entire internals to not use property arrays. Now the library supports nested objects.
I also added a few tests, but the naming for those and all the edge case testing is not yet complete, I will do that tomorrow.

**Comment by AB1908** [comment]
I need a little advice. I want to be able to write tests of the sort:

```js
expect(app.vault.cachedRead(tfile)).toEqual("---\nfield: value\n---");
await addFieldToFile("newfield", "newvalue", tfile, plugin);
expect(app.vault.modify).toHaveBeenCalledTimes(1);
expect(app.vault.cachedRead(tfile)).toEqual("---\nfield: value\nnewfield: newvalue\n---");
```

so that the behavior of the API remains stable despite changing the internals, which is what any user would expect. How would one do this without setting up a ton of mocks? I feel that by testing certain internal components, such as the value received by the `stringifyFrontmatter` field, we are tightly coupling the tests to the nature of the implementation which can be quite brittle.

**Comment by claremacrae** [comment]
> I need a little advice. I want to be able to write tests of the sort:
> 
> ```js
> expect(app.vault.cachedRead(tfile)).toEqual("---\nfield: value\n---");
> await addFieldToFile("newfield", "newvalue", tfile, plugin);
> expect(app.vault.modify).toHaveBeenCalledTimes(1);
> expect(app.vault.cachedRead(tfile)).toEqual("---\nfield: value\nnewfield: newvalue\n---");
> ```
> 
> so that the behavior of the API remains stable despite changing the internals, which is what any user would expect. How would one do this without setting up a ton of mocks? I feel that by testing certain internal components, such as the value received by the `stringifyFrontmatter` field, we are tightly coupling the tests to the nature of the implementation which can be quite brittle.

Let's set up a pairing session to talk specifically about that.

**Pull request merged**
